### ISSUE TITLE
Remove the need for an Express error handler

### ISSUE THREAD

**Issue by luismiramirez** [appsignal/appsignal-nodejs#1044]
The OpenTelemetry Express instrumentation now automatically records exceptions without the need of an error handler.

See: https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1657

### ToDo

- [ ] Update the integration dependency
- [ ] Update test-setups
- [ ] Update the docs

**Comment by unflxw** [comment]
Going by the linked PR, it seems that it only records exceptions in middlewares? Does that cover our needs?

**Comment by luismiramirez** [comment]
That change doesn't cover our needs.

Here's an open issue reporting problems with the change: https://github.com/open-telemetry/opentelemetry-js-contrib/issues/2146
