### ISSUE TITLE
Config option apiKey should be pushApiKey

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-nodejs#470]
The Node.js integration uses `apiKey` for the `push_api_key` config option used by the Elixir and Ruby integrations. They should be the same.

## TODO

- [x] Add a `pushApiKey` config option - https://github.com/appsignal/appsignal-nodejs/pull/507
- [x] Deprecate the `apiKey` config option - https://github.com/appsignal/appsignal-nodejs/pull/507
  - [x] If the `apiKey` config option is set, it should set the `pushApiKey` config option as a fallback.
  - [x] Print a warning to app STDOUT when the `apiKey` config option is set.
- [x] Update docs - https://github.com/appsignal/appsignal-docs/pull/504

**Comment by tombruijn** [comment]
@jeffkreeftmeijer @thijsc Do you remember why it's called `apiKey` now and can we rename it to `pushApiKey`?

**Comment by jeffkreeftmeijer** [comment]
No, and yes. I think we can update this, as long as the change is backward compatible.

**Comment by tombruijn** [comment]
We're moving forward with this. I'm removing the discuss label.

**Comment by tombruijn** [comment]
Fixed in https://github.com/appsignal/appsignal-nodejs/pull/507
