### ISSUE TITLE
Log source doesn't default to "stdout" on Heroku

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-nodejs#495]
On Heroku we should default the log option (for the integration and extension) to "stdout".

Note: the `log` config option does not affect the appsignal-agent log source, it will always log to file.

Sources:

- Ruby implementation: https://github.com/appsignal/appsignal-ruby/blob/e2fd3f928a7cfbcffd9c9a10a32e5b2d49104d91/lib/appsignal/config.rb#L330

## TODO

- [x] Add check for Heroku, we use the `DYNO` env var is set to any value.
- [x] Add `system` config source, also used in the diagnose report
- [x] Set `log` config option by default to `stdout` on when Heroku is detected

**Comment by tombruijn** [comment]
Let's also check if Dokku needs to behave the same way and make an exception otherwise.
