### ISSUE TITLE
Add "override" config source

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-nodejs#568]
As discussed in https://github.com/appsignal/integration-guide/pull/128, we want to track some config options in the "override" source.

## TODO

- [ ] Add "override" config source to the Config module
- [ ] Move the backwards compatability logic to be set through the "override" source, rather than after the fact as is done now
    - Move the overrides that are now reported in the "system" to the "override" source
    - Check if this actually applies to any config options for Node.js
- [ ] Update the diagnose report to report the "override" source
- [ ] Update Node.js load order docs page to mention the "override" source https://docs.appsignal.com/nodejs/configuration/load-order.html
