### ISSUE TITLE
Map requestHeaders to OTel's HTTP headersToSpanAttributes config option

### ISSUE THREAD

**Issue by luismiramirez** [appsignal/appsignal-nodejs#697]
OpenTelemetry's HTTP official instrumentation provides the ability to add request headers as span attributes. It can be done via the [headersToSpanAttributes](https://github.com/open-telemetry/opentelemetry-js/blob/main/experimental/packages/opentelemetry-instrumentation-http/src/types.ts#L107) config option.

As with our `requestHeaders` config option, it acts as an allow list. 

## ToDo

- [x] Map our `requestHeaders` config option to the OpenTelemetry's one (Done in: https://github.com/appsignal/appsignal-nodejs/pull/707)
- [x] Make the extension parse arrays of strings
- [x] Make the agent's HTTP server parse an array of strings

**Comment by tombruijn** [comment]
We may  need to do this in the extension, because our protocol doesn't support array values for root span attributes I think.
