### ISSUE TITLE
Add OpenTelemetry Postgres instrumentation

### ISSUE THREAD

**Issue by luismiramirez** [appsignal/appsignal-nodejs#698]
As with MySQL and Redis clients, add automatic instrumentation for Postgres

OTel package: https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/plugins/node/opentelemetry-instrumentation-pg

## ToDo
- [x] Add extractor in the agent https://github.com/appsignal/appsignal-agent/pull/797
- [x] Add automatic instrumentation https://github.com/appsignal/appsignal-nodejs/pull/720
- [x] Add example application https://github.com/appsignal/appsignal-nodejs/pull/720

[skip blogpost]
