### ISSUE TITLE
Add OpenTelemetry GraphQL instrumentation

### ISSUE THREAD

**Issue by luismiramirez** [appsignal/appsignal-nodejs#699]
Add support for GraphQL queries in the integration using OpenTelemetry [contrib package](https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/plugins/node/opentelemetry-instrumentation-graphql)

As GraphQL is supported globally, there's no need for a separated Apollo package anymore.

## ToDo
- [x] Add extractor in the agent
- [x] Add automatic instrumentation
- [x] Add example application

[skip blogpost]
