### ISSUE TITLE
Next.js + Webpack incompatibility

### ISSUE THREAD

**Issue by luismiramirez** [appsignal/appsignal-nodejs#928]
### Root report

This was discovered after a [customer reported](https://app.intercom.com/a/inbox/yzor8gyw/inbox/conversation/16410700223033) an error related to the `extension.node` binary file throwing an error when being read by Next.js's Webpack.

I was able to get through that error by using a [third-party loader](https://github.com/webpack-contrib/node-loader) for webpack that allows you to get Node binary files into the bundle.

Here's how the updated Next.js app config looks after adding the dependency to the project:

```js
module.exports = {
  webpack: (config, _options) => {
    config.module.rules.push({
      test: /\.node$/i,
      loader: "node-loader",
    })
    return config
  }
}
```

---

### Actual issue

After fixing the extension binary file, the app server logged this:

```
  x Legacy octal escape is not permitted in strict mode
    ,-[/Users/luismiramirez/code/winston-logging/node_modules/ansi-color/lib/ansi-color.js:34:1]
 34 |   for(var i=0, attr; attr = color_attrs[i]; i++) {
 35 |     ansi_str += "\033[" + ANSI_CODES[attr] + "m";
 36 |   }
 37 |   ansi_str += str + "\033[" + ANSI_CODES["off"] + "m";
    :                      ^^
 38 |   return ansi_str;
 39 | };
    `----
```

This comes from a package called `ansi-color`, which is the end of a dependency tree that starts from the `@opentelemetry/sdk-node`, which is a dependency of our integration.

- `@opentelemetry/sdk-node`
  - `@opentelemetry/exporter-jaeger`
    - `jaeger-client`
      - `thriftrw`
        - `bufrw` 

Another user already reported this issue to the OpenTelemetry team at: https://github.com/open-telemetry/opentelemetry-js/issues/3759. The OpenTelemetry team released a fix for this here: https://github.com/open-telemetry/opentelemetry-js/pull/3739.

I updated our `@opentelemetry/sdk-node` dependency to the latest version with no success. Also found out that other users are in the same situation, so the issue still needs to be closed.

OpenTelemetry's team progress on the issue can be tracked here: https://github.com/open-telemetry/opentelemetry-js/issues/3759.

---

## ToDo

- [ ] Research if there's a way to work around this until OpenTelemetry releases a fix
- [ ] Implement it and publish
- [ ] Notify users of fix:
  - [ ] https://app.intercom.com/a/inbox/yzor8gyw/inbox/shared/all/conversation/16410700250112#part_id=comment-16410700250112-21909534813

**Comment by unflxw** [comment]
The next OpenTelemetry release ([changelog](https://github.com/open-telemetry/opentelemetry-js/blob/24997089daf6d422494d112cf5531fe115eaa201/experimental/CHANGELOG.md#unreleased)) should remove the dependency on `@opentelemetry/exporter-jaeger`, nicely working around this whole problem for us.

There is a customer waiting on the fix that should be notified: [Intercom link](https://app.intercom.com/a/inbox/yzor8gyw/inbox/shared/all/conversation/16410700250112#part_id=comment-16410700250112-21909534813)

**Comment by luismiramirez** [comment]
Awesome! I'll keep an eye on this to upgrade the dependencies as soon as it's released.

**Comment by unflxw** [comment]
Update: something went wrong with that fix -- a further fix was added by @luismiramirez [in this PR](https://github.com/open-telemetry/opentelemetry-js/pull/4214), and [it has now been merged](https://github.com/open-telemetry/opentelemetry-js/blob/1c7d7a354281c720e7229d3d5498bbec8d3b2b8d/experimental/CHANGELOG.md#bug-bug-fix). So the next OpenTelemetry version should include the fix.

**Comment by unflxw** [comment]
Update update: version 0.45.0 was released, which includes the fix. Let's update the dependencies to bring that in.

**Comment by unflxw** [comment]
We'll be bumping the dependency range on `@opentelemetry/sdk-node` in the next release to make sure no one runs into this issue going forward. In the meantime, if you're affected by this issue, running `npm update @opentelemetry/sdk-node` should fix it.
